// @ts-nocheck
import type { HarmonyStyle, HarmonyType, TaroStyleType, TaroTextStyleType } from './type';
export { HarmonyStyle, HarmonyType, TaroStyleType, TaroTextStyleType };
export default class StyleSheet {
    hmStyle: HarmonyStyle;
    get display(): "none" | "block" | "flex" | undefined;
    get position(): "fixed" | "relative" | "absolute" | undefined;
    get padding(): string;
    get paddingTop(): any;
    get paddingBottom(): any;
    get paddingLeft(): any;
    get paddingRight(): any;
    get margin(): string;
    get marginTop(): any;
    get marginBottom(): any;
    get marginLeft(): any;
    get marginRight(): any;
    get top(): any;
    get left(): any;
    get right(): any;
    get bottom(): any;
    get flex(): string;
    get flexBasis(): string | number | undefined;
    get flexGrow(): number;
    get flexShrink(): number;
    get alignSelf(): string;
    get flexDirection(): string;
    get justifyContent(): string;
    get alignItems(): string;
    get alignContent(): string;
    get flexWrap(): string;
    get width(): any;
    get height(): any;
    get minHeight(): any;
    get maxHeight(): any;
    get minWidth(): any;
    get maxWidth(): any;
    get background(): string;
    get backgroundColor(): any;
    get backgroundImage(): any;
    get backgroundRepeat(): "repeat-x" | "repeat-y" | "no-repeat" | "repeat" | undefined;
    get backgroundSize(): string | undefined;
    get backgroundPosition(): string | undefined;
    get border(): string;
    get borderWidth(): any;
    get borderLeftWidth(): any;
    get borderRightWidth(): any;
    get borderTopWidth(): any;
    get borderBottomWidth(): any;
    get borderColor(): any;
    get borderLeftColor(): any;
    get borderRightColor(): any;
    get borderTopColor(): any;
    get borderBottomColor(): any;
    get borderStyle(): string;
    get borderLeftStyle(): string;
    get borderRightStyle(): string;
    get borderTopStyle(): string;
    get borderBottomStyle(): string;
    get borderRadius(): any;
    get borderTopLeftRadius(): any;
    get borderTopRightRadius(): any;
    get borderBottomLeftRadius(): any;
    get borderBottomRightRadius(): any;
    get zIndex(): number | undefined;
    get opacity(): any;
    get overflow(): "visible" | "hidden";
    get focus(): boolean;
    get color(): any;
    get fontSize(): any;
    get fontWeight(): any;
    get fontStyle(): "" | "normal" | "italic";
    get fontFamily(): any;
    get textAlign(): "" | "center" | "left" | "right";
    get verticalAlign(): "" | "bottom" | "middle" | "top";
    get lineHeight(): any;
    get letterSpacing(): string | number | undefined;
    get textDecoration(): "none" | "" | "underline" | "overline" | "line-through";
    get textOverflow(): "none" | "clip" | "ellipsis" | "marquee" | undefined;
    get WebkitLineClamp(): number;
    get transform(): HarmonyType.Transform.Transform | undefined;
    get transformOrigin(): HarmonyType.Transform.Origin | undefined;
    get content(): any;
}
